@echo off
echo Starting Frozen Basket Web App...
cd "c:\Users\LENOVO\Documents\forzen basket\web\mix-builder-restoration"
echo Installing dependencies if needed...
call npm install
echo Starting development server...
call npm run dev
pause
